### PR TITLE
Updated contact info

### PR DESCRIPTION
**Pull request by jkordani**
Updated Readme.org and add file with my name and email.

I don't know if this is a workflow step you're expecting, but I'm using github to make the pull request to merge my branch to master.  If this isn't correct please advise.

### CODE REVIEW

**Comment by jkordani** [comment]
Is deleting branches in simple cases like this considered good practice? or...

**Comment by wvxvw** [comment]
Pull request may be a bit of an overkill, but if it works for you, I'm
OK with it. There's no reason to delete the branch now. The idea was
to have at least a branch per committer to avoid queuing. But if you
think that there's something you don't want to be in the repository
(eg. you committed some confidential info), then the way to handle it
would be to rewrite history by using something like git filter-branch,
but it seems like there's nothing of that kind in the repository now.

**Comment by jkordani** [comment]
Regarding the branch, I see what you mean.  Regarding how to get my branch changes into master, I don't know enough to know a different course of action regarding the use of the pull request.

**Comment by wvxvw** [comment]
Well, the idea behind pull requests is usually as follows: there is an
established project with a lot of its own development traffic. You
want to modify some (typically small) bit of functionality in that
project. So, you fork from it, add your changes, then you write to the
person responsible for the original project asking them to merge your
changes (thus, they typically come with an e-mail / note explaining
why did you make the changes), they also typically come in a form of a
patch, rather than by pushing the change into repository.

In our case, that's a bit too much bureaucracy. So, the idea is as
follows: you check out the repository, create a branch where you make
your changes, commit the changes to your branch, push your branch,
merge master into your branch, then push the changes back into master.
Typical scenario, of working from command line:

$ git pull
$ git checkout -b my-branch
# -b is for creating a branch, omit it, if you want to work on your old branch

$ echo "my@email" > README.org
$ commit -m "Added my email to README"
$ push -u my-branch
# -u means "set upstream" i.e. create a branch with the same name on
# remote machine, then set local branch to track that new branch,
# then push changes into that new branch (you need to do this only once
# after you forked from master).

$ git merge master
# resolve conflicts if any
$ git push my-branch:master

In Magit:

F F ; pull
b c my-branch ; create branch
; edit the README
P -u P ; push (-u for "set upstream)
b b master ; switch to master branch
F F ; pull
b b my-branch ; switch back to your branch
m m master ; merge master into your branch
e ; resolve conflicts, if any, otherwise you'll be prompted with
generated commit message
C-c C-c ; confirm merge commit

P o master ; push changes to the master branch

**Comment by wvxvw** [comment]
PS. You are of course welcome to experiment with it. No worries, you
won't break anything :)

**Pull request merged**
